require("config.lazy")
require("config.file-explorer").setup()
require("config.theme").setup()
require("config.lsp")
require("config.hardtime").setup()
require("config.options")
require("config.keymaps")
