-- vim.lsp.config('rust-analyzer', {
--   settings = {
--     ['rust-analyzer'] = {
--       assist = {
--         importGranularity = 'module',
--         importPrefix = 'by_self',
--       },
--       cargo = {
--         allFeatures = true,
--       },
--       checkOnSave = {
--         command = 'clippy',
--       },
--     },
--   },
-- })
--
